# Generated by Django 5.1.1 on 2024-10-09 23:05

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('goal_achieved', 'Goal Achieved')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Walking', 'Walking'), ('Weightlifting', 'Weightlifting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
