# Generated by Django 5.1.1 on 2024-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_rename_user_activity_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
